import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "../globals.css"; // Adjusted import path

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LangLayoutProps {
  children: React.ReactNode;
  params: { lang: string };
}

export default async function LangLayout({
  children,
  params,
}: LangLayoutProps) {
  const { lang } = params; // No need to await params here, it's already an object
  // Dictionary is now loaded in page.tsx, but we can still load it here if needed for layout specific translations
  // const dictionary = await getDictionary(lang);
  return (
    <div
      className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
    >
      {children}
    </div>
  );
}
